# name: Storybook
# on:
#   push:
#     branches:
#       - main # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder
# permissions:
#   contents: write

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v4

#       - name: Install and Build
#         run: |
#           yarn
#           yarn build-storybook

#       - name: Deploy ğŸš€
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           branch: gh-pages
#           folder: storybook-static # output folder from `yarn build-storybook`
